language: node_js
node_js:
- '0.12'

env:
  global:
  - GH_REF=github.com/climatescope/climatescope-2015.git
  - DEPLOY_BRANCH=publish
  - secure: SpczO7gxYI8LpdI9gQL8Ai18rSjTsL79aEVnyhou0luEaDLN+K/vo89CthavMefrZF1L//qD9P2FkoHCBtRaFrruhQzdwXLNxWlO9aNdmAi5fWMwH4iCoEjfu0rIV/sNpno7hiVpTX9mCDcWOxEHhkJKFdCxDBW4PMem5cg2nkSJ2EadSTdRtUDITqJYxHNa5A4wRYnXlYEV0RIjf5Tu+I0in4Zp4cjjVdKaLjsnSF7qdhZmGEFsivUvWjFXcZMjT2LMMnGkX0FYIBPNPXF22wQ1nViguQ4OUUeQlkLPh896wydqiTyRuQMolGBgjQKiJeCoQh+i7pL9cvkx8RKlBDBhYmfQ6SjQdG33399o9fDXN9isCsxwUZpsGZXE8FQHp9gKpriOp38NbxRFD6trD5h+HTZ7uyBcwItt8QjwfI7H1+OMT82YsWVJOGXkl7YQNTpawWOAhDOhNbRRYaaGxZJHbxwGDikWM6H0IBg3UBcaJ5NxxWjILuCB4qEhmK8nmxxIfgBWfnu70s0jI3+c7YtSF6zcQpE7q8pjwgoQEoGX8W//e4qUMzYvHRhvgPdCB08LImzd51f1ErtMByuuWcTNrUcdwLdYJpx0avgslWgg+dBCnJCwyYzXvF+iQP2o/nAUKropdOqXbl8qydHnAQxKillygrARW4FH3bcvKjg=

before_install:
- chmod +x ./.build_scripts/deploy.sh

script:
- gulp prod

after_success:
- ./.build_scripts/deploy.sh